dictionaries:
  - en
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - "*.tsx.snap"
  - "packages/icons/src/natds-icons.swift"
  - "node_modules/**/*"
  - "packages/docs/dist/**/*"
excluded_words:
  - Aboukhadijeh
  - Ashkenas
  - brand
  - cjs
  - date-fns
  - dedupe
  - eqeqeq
  - feross
  - fileurl
  - filled
  - filled-brand-naturarosacea
  - filled-navigation
  - Fira
  - FiraCode-Retina
  - function-paren-newline
  - Holowaychuk
  - hugex
  - hugexx
  - iml
  - Isonen
  - javascript-mutator
  - Kirollos
  - largex
  - Lubbe
  - Lichtnow
  - Lucida
  - Lyrio
  - Matheus
  - mediumx
  - Mui
  - MuiAlert
  - MuiAlertTitle
  - MuiAvatar
  - MuiBadge
  - MuiButton
  - MuiButtonGroup
  - MuiChip
  - MuiExpansionPanel
  - MuiExpansionPanelSummary
  - MuiFormHelperText
  - MuiFormLabel
  - MuiListItem
  - MuiIconButton
  - MuiInputAdornment
  - MuiInputBase
  - MuiInputLabel
  - MuiSelect
  - MuiSvgIcon
  - MuiTab
  - MuiTextField
  - MuiToolbar
  - multiline-comment-style
  - multiline-ternary
  - natds
  - natDsIcons
  - natdsIcons
  - natds-icons
  - natds-styles
  - natds-web
  - natdsWeb
  - natura
  - naturacosmeticos
  - naturarosacea
  - Nunito
  - oga
  - outlined
  - outlined-action
  - outlined-action-lightoff
  - outlined-action-lighton
  - outlined-action-selectedalllines
  - outlined-action-shareios
  - outlined-content
  - outlined-content-christmascard
  - outlined-content-planb
  - outlined-default-mockup
  - outlined-finance-shoppingcartproduct
  - outlined-place-waze
  - outlined-social-groupofpeople
  - preferBuiltins
  - Saraiva
  - Schlinkert
  - semix
  - Sindre
  - Slobodskoi
  - Sorhus
  - space-before-function-paren
  - stryker
  - stryker-mutator
  - stryker-tmp
  - tcm
  - testc
  - Tiancheng
  - transpilers
  - typoci
  - Vagner
  - Vizir
  - wav
  - webfont
  - Zivolo
