declare const styles: {
  readonly "natds-icons": string;
  readonly "natds-icons-lg": string;
  readonly "natds-icons-xs": string;
  readonly "natds-icons-sm": string;
  readonly "natds-icons-1x": string;
  readonly "natds-icons-2x": string;
  readonly "natds-icons-3x": string;
  readonly "natds-icons-4x": string;
  readonly "natds-icons-5x": string;
  readonly "natds-icons-6x": string;
  readonly "natds-icons-7x": string;
  readonly "natds-icons-8x": string;
  readonly "natds-icons-9x": string;
  readonly "natds-icons-10x": string;
  readonly "natds-icons-fw": string;
  readonly "natds-icons-border": string;
  readonly "natds-icons-pull-left": string;
  readonly "natds-icons-pull-right": string;
  readonly "natds-icons-autofilter-outlined": string;
  readonly "natds-icons-cancel-filled": string;
  readonly "natds-icons-cancel-outlined": string;
  readonly "natds-icons-check-filled": string;
  readonly "natds-icons-check-outlined": string;
  readonly "natds-icons-pause-filled": string;
  readonly "natds-icons-play-filled": string;
  readonly "natds-icons-send-outlined": string;
};
export = styles;

