declare const styles: {
  readonly "natds-icons": string;
  readonly "natds-icons-lg": string;
  readonly "natds-icons-xs": string;
  readonly "natds-icons-sm": string;
  readonly "natds-icons-1x": string;
  readonly "natds-icons-2x": string;
  readonly "natds-icons-3x": string;
  readonly "natds-icons-4x": string;
  readonly "natds-icons-5x": string;
  readonly "natds-icons-6x": string;
  readonly "natds-icons-7x": string;
  readonly "natds-icons-8x": string;
  readonly "natds-icons-9x": string;
  readonly "natds-icons-10x": string;
  readonly "natds-icons-fw": string;
  readonly "natds-icons-border": string;
  readonly "natds-icons-pull-left": string;
  readonly "natds-icons-pull-right": string;
  readonly "natds-icons-filled-alert-cancel": string;
  readonly "natds-icons-filled-alert-check": string;
  readonly "natds-icons-filled-media-pause": string;
  readonly "natds-icons-filled-media-play": string;
  readonly "natds-icons-outlined-action-autofilter": string;
  readonly "natds-icons-outlined-action-send": string;
  readonly "natds-icons-outlined-alert-cancel": string;
  readonly "natds-icons-outlined-alert-check": string;
};
export = styles;

