/* eslint-disable sort-keys */
import { IColorThemeTokens } from "../IColorThemeTokens";

export const avonDarkColorTokens: IColorThemeTokens = {
  colorPrimary: "#F091C9",
  colorOnPrimary: "#000000",
  colorPrimaryLight: "#FFC3FC",
  colorOnPrimaryLight: "#000000",
  colorPrimaryDark: "#BC6198",
  colorOnPrimaryDark: "#000000",
  colorSecondary: "#E9E9E9",
  colorOnSecondary: "#333333",
  colorSecondaryLight: "#FFFFFF",
  colorOnSecondaryLight: "#333333",
  colorSecondaryDark: "#B7B7B7",
  colorOnSecondaryDark: "#333333",
  colorBackground: "#121212",
  colorOnBackground: "#FFFFFF",
  colorSurface: "#333333",
  colorOnSurface: "#FFFFFF",
  colorHighlight: "#FFFFFF",
  colorHighEmphasis: "#FAFAFA",
  colorMediumEmphasis: "#BBBBBB",
  colorLowEmphasis: "#777777",
  colorLink: "#227BBD",
  colorOnLink: "#FFFFFF",
  colorSuccess: "#569A32",
  colorOnSuccess: "#FFFFFF",
  colorWarning: "#FCC433",
  colorOnWarning: "#333333",
  colorAlert: "#E74627",
  colorOnAlert: "#FFFFFFF",
};
