/* eslint-disable sort-keys */
import { IColorThemeTokens } from "../IColorThemeTokens";

export const avonLightColorTokens: IColorThemeTokens = {
  colorPrimary: "#DE0085",
  colorOnPrimary: "#FFFFFF",
  colorPrimaryLight: "#FF56B5",
  colorOnPrimaryLight: "#000000",
  colorPrimaryDark: "#A70058",
  colorOnPrimaryDark: "#FFFFFF",
  colorSecondary: "#E9E9E9",
  colorOnSecondary: "#333333",
  colorSecondaryLight: "#FFFFFF",
  colorOnSecondaryLight: "#333333",
  colorSecondaryDark: "#B7B7B7",
  colorOnSecondaryDark: "#333333",
  colorBackground: "#FAFAFA",
  colorOnBackground: "#333333",
  colorSurface: "#FFFFFF",
  colorOnSurface: "#333333",
  colorHighlight: "#000000",
  colorHighEmphasis: "#333333",
  colorMediumEmphasis: "#777777",
  colorLowEmphasis: "#BBBBBB",
  colorLink: "#227BBD",
  colorOnLink: "#FFFFFF",
  colorSuccess: "#569A32",
  colorOnSuccess: "#FFFFFF",
  colorWarning: "#FCC433",
  colorOnWarning: "#333333",
  colorAlert: "#E74627",
  colorOnAlert: "#FFFFFF",
};
