/* eslint-disable sort-keys */
import { IColorThemeTokens } from "../IColorThemeTokens";

export const theBodyShopLightColorTokens: IColorThemeTokens = {
  colorPrimary: "#004236",
  colorOnPrimary: "#FFFFFF",
  colorPrimaryLight: "#356D60",
  colorOnPrimaryLight: "#FFFFFF",
  colorPrimaryDark: "#001D10",
  colorOnPrimaryDark: "#FFFFFF",
  colorSecondary: "#A55F53",
  colorOnSecondary: "#FFFFFF",
  colorSecondaryLight: "#D98D7F",
  colorOnSecondaryLight: "#FFFFFF",
  colorSecondaryDark: "#73342A",
  colorOnSecondaryDark: "#FFFFFF",
  colorBackground: "#FAFAFA",
  colorOnBackground: "#333333",
  colorSurface: "#FFFFFF",
  colorOnSurface: "#333333",
  colorHighlight: "#000000",
  colorHighEmphasis: "#333333",
  colorMediumEmphasis: "#777777",
  colorLowEmphasis: "#BBBBBB",
  colorLink: "#227BBD",
  colorOnLink: "#FFFFFF",
  colorSuccess: "#569A32",
  colorOnSuccess: "#FFFFFF",
  colorWarning: "#FCC433",
  colorOnWarning: "#333333",
  colorAlert: "#E74627",
  colorOnAlert: "#FFFFFF",
};
