/* eslint-disable sort-keys */
import { IColorThemeTokens } from "../IColorThemeTokens";

export const theBodyShopDarkColorTokens: IColorThemeTokens = {
  colorPrimary: "#62B3AE",
  colorOnPrimary: "#000000",
  colorPrimaryLight: "#94E5E0",
  colorOnPrimaryLight: "#000000",
  colorPrimaryDark: "#2F837F",
  colorOnPrimaryDark: "#000000",
  colorSecondary: "#D2AD93",
  colorOnSecondary: "#000000",
  colorSecondaryLight: "#FFDFC4",
  colorOnSecondaryLight: "#000000",
  colorSecondaryDark: "#A07E65",
  colorOnSecondaryDark: "#000000",
  colorBackground: "#121212",
  colorOnBackground: "#FFFFFF",
  colorSurface: "#333333",
  colorOnSurface: "#FFFFFF",
  colorHighlight: "#FFFFFF",
  colorHighEmphasis: "#FAFAFA",
  colorMediumEmphasis: "#BBBBBB",
  colorLowEmphasis: "#777777",
  colorLink: "#227BBD",
  colorOnLink: "#FFFFFF",
  colorSuccess: "#569A32",
  colorOnSuccess: "#FFFFFF",
  colorWarning: "#FCC433",
  colorOnWarning: "#333333",
  colorAlert: "#E74627",
  colorOnAlert: "#FFFFFF",
};
