export interface IColorThemeTokens {
  colorPrimary: string;
  colorOnPrimary: string;
  colorPrimaryLight: string;
  colorOnPrimaryLight: string;
  colorPrimaryDark: string;
  colorOnPrimaryDark: string;
  colorSecondary: string;
  colorOnSecondary: string;
  colorSecondaryLight: string;
  colorOnSecondaryLight: string;
  colorSecondaryDark: string;
  colorOnSecondaryDark: string;
  colorBackground: string;
  colorOnBackground: string;
  colorSurface: string;
  colorOnSurface: string;
  colorHighlight: string;
  colorHighEmphasis: string;
  colorMediumEmphasis: string;
  colorLowEmphasis: string;
  colorLink: string;
  colorSuccess: string;
  colorOnSuccess: string;
  colorWarning: string;
  colorOnWarning: string;
  colorAlert: string;
  colorOnAlert: string;
}
